/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { TransactionOverrides } from ".";
import { CreateAndAddModules } from "./CreateAndAddModules";

export class CreateAndAddModulesFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: TransactionOverrides): Promise<CreateAndAddModules> {
    return super.deploy(overrides) as Promise<CreateAndAddModules>;
  }
  getDeployTransaction(overrides?: TransactionOverrides): UnsignedTransaction {
    return super.getDeployTransaction(overrides);
  }
  attach(address: string): CreateAndAddModules {
    return super.attach(address) as CreateAndAddModules;
  }
  connect(signer: Signer): CreateAndAddModulesFactory {
    return super.connect(signer) as CreateAndAddModulesFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CreateAndAddModules {
    return new Contract(address, _abi, signerOrProvider) as CreateAndAddModules;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "proxyFactory",
        type: "address"
      },
      {
        name: "data",
        type: "bytes"
      }
    ],
    name: "createAndAddModules",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        name: "module",
        type: "address"
      }
    ],
    name: "enableModule",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  }
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061029a806100206000396000f3fe608060405234801561001057600080fd5b5060043610610052577c0100000000000000000000000000000000000000000000000000000000600035046360df7f588114610057578063610b59251461011c575b600080fd5b61011a6004803603604081101561006d57600080fd5b73ffffffffffffffffffffffffffffffffffffffff82351691908101906040810160208201356401000000008111156100a557600080fd5b8201836020820111156100b757600080fd5b803590602001918460018302840111640100000000831117156100d957600080fd5b91908080601f01602080910402602001604051908101604052809392919081815260200183838082843760009201919091525092955061014f945050505050565b005b61011a6004803603602081101561013257600080fd5b503573ffffffffffffffffffffffffffffffffffffffff16610052565b80516000805b828110156102675780840160200151818501604001604051600060208285858c5af4141561018257600080fd5b73ffffffffffffffffffffffffffffffffffffffff8151169450602080601f85010402602001840193505050503073ffffffffffffffffffffffffffffffffffffffff1663610b5925836040518263ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001915050600060405180830381600087803b15801561024a57600080fd5b505af115801561025e573d6000803e3d6000fd5b50505050610155565b505050505056fea165627a7a72305820e7800380b821d639189ed06b6fade86e30b1c062e3dba231413e456f91c53b610029";
