/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface DelegateConstructorProxyInterface extends Interface {
  functions: {};

  events: {};
}

export class DelegateConstructorProxy extends Contract {
  connect(
    signerOrProvider: Signer | Provider | string
  ): DelegateConstructorProxy;
  attach(addressOrName: string): DelegateConstructorProxy;
  deployed(): Promise<DelegateConstructorProxy>;

  on(event: EventFilter | string, listener: Listener): DelegateConstructorProxy;
  once(
    event: EventFilter | string,
    listener: Listener
  ): DelegateConstructorProxy;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): DelegateConstructorProxy;
  removeAllListeners(eventName: EventFilter | string): DelegateConstructorProxy;
  removeListener(eventName: any, listener: Listener): DelegateConstructorProxy;

  interface: DelegateConstructorProxyInterface;

  functions: {};

  filters: {};

  estimate: {};
}
