/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { ERC1155TokenReceiver } from "./ERC1155TokenReceiver";

export class ERC1155TokenReceiverFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC1155TokenReceiver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC1155TokenReceiver;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_operator",
        type: "address"
      },
      {
        name: "_from",
        type: "address"
      },
      {
        name: "_ids",
        type: "uint256[]"
      },
      {
        name: "_values",
        type: "uint256[]"
      },
      {
        name: "_data",
        type: "bytes"
      }
    ],
    name: "onERC1155BatchReceived",
    outputs: [
      {
        name: "",
        type: "bytes4"
      }
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        name: "_operator",
        type: "address"
      },
      {
        name: "_from",
        type: "address"
      },
      {
        name: "_id",
        type: "uint256"
      },
      {
        name: "_value",
        type: "uint256"
      },
      {
        name: "_data",
        type: "bytes"
      }
    ],
    name: "onERC1155Received",
    outputs: [
      {
        name: "",
        type: "bytes4"
      }
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  }
];
