/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ERC777TokensRecipientInterface extends Interface {
  functions: {
    tokensReceived: TypedFunctionDescription<{
      encode([operator, from, to, amount, data, operatorData]: [
        string,
        string,
        string,
        BigNumberish,
        Arrayish,
        Arrayish
      ]): string;
    }>;
  };

  events: {};
}

export class ERC777TokensRecipient extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ERC777TokensRecipient;
  attach(addressOrName: string): ERC777TokensRecipient;
  deployed(): Promise<ERC777TokensRecipient>;

  on(event: EventFilter | string, listener: Listener): ERC777TokensRecipient;
  once(event: EventFilter | string, listener: Listener): ERC777TokensRecipient;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): ERC777TokensRecipient;
  removeAllListeners(eventName: EventFilter | string): ERC777TokensRecipient;
  removeListener(eventName: any, listener: Listener): ERC777TokensRecipient;

  interface: ERC777TokensRecipientInterface;

  functions: {
    tokensReceived(
      operator: string,
      from: string,
      to: string,
      amount: BigNumberish,
      data: Arrayish,
      operatorData: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  tokensReceived(
    operator: string,
    from: string,
    to: string,
    amount: BigNumberish,
    data: Arrayish,
    operatorData: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    tokensReceived(
      operator: string,
      from: string,
      to: string,
      amount: BigNumberish,
      data: Arrayish,
      operatorData: Arrayish
    ): Promise<BigNumber>;
  };
}
