/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ERC721TokenReceiverInterface extends Interface {
  functions: {
    onERC721Received: TypedFunctionDescription<{
      encode([_operator, _from, _tokenId, _data]: [
        string,
        string,
        BigNumberish,
        Arrayish
      ]): string;
    }>;
  };

  events: {};
}

export class ERC721TokenReceiver extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ERC721TokenReceiver;
  attach(addressOrName: string): ERC721TokenReceiver;
  deployed(): Promise<ERC721TokenReceiver>;

  on(event: EventFilter | string, listener: Listener): ERC721TokenReceiver;
  once(event: EventFilter | string, listener: Listener): ERC721TokenReceiver;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): ERC721TokenReceiver;
  removeAllListeners(eventName: EventFilter | string): ERC721TokenReceiver;
  removeListener(eventName: any, listener: Listener): ERC721TokenReceiver;

  interface: ERC721TokenReceiverInterface;

  functions: {
    onERC721Received(
      _operator: string,
      _from: string,
      _tokenId: BigNumberish,
      _data: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  onERC721Received(
    _operator: string,
    _from: string,
    _tokenId: BigNumberish,
    _data: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    onERC721Received(
      _operator: string,
      _from: string,
      _tokenId: BigNumberish,
      _data: Arrayish
    ): Promise<BigNumber>;
  };
}
