/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { ERC777TokensRecipient } from "./ERC777TokensRecipient";

export class ERC777TokensRecipientFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC777TokensRecipient {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC777TokensRecipient;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "operator",
        type: "address"
      },
      {
        name: "from",
        type: "address"
      },
      {
        name: "to",
        type: "address"
      },
      {
        name: "amount",
        type: "uint256"
      },
      {
        name: "data",
        type: "bytes"
      },
      {
        name: "operatorData",
        type: "bytes"
      }
    ],
    name: "tokensReceived",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  }
];
