/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface EtherPaymentFallbackInterface extends Interface {
  functions: {};

  events: {};
}

export class EtherPaymentFallback extends Contract {
  connect(signerOrProvider: Signer | Provider | string): EtherPaymentFallback;
  attach(addressOrName: string): EtherPaymentFallback;
  deployed(): Promise<EtherPaymentFallback>;

  on(event: EventFilter | string, listener: Listener): EtherPaymentFallback;
  once(event: EventFilter | string, listener: Listener): EtherPaymentFallback;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): EtherPaymentFallback;
  removeAllListeners(eventName: EventFilter | string): EtherPaymentFallback;
  removeListener(eventName: any, listener: Listener): EtherPaymentFallback;

  interface: EtherPaymentFallbackInterface;

  functions: {};

  filters: {};

  estimate: {};
}
