/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface FallbackManagerInterface extends Interface {
  functions: {
    setFallbackHandler: TypedFunctionDescription<{
      encode([handler]: [string]): string;
    }>;
  };

  events: {};
}

export class FallbackManager extends Contract {
  connect(signerOrProvider: Signer | Provider | string): FallbackManager;
  attach(addressOrName: string): FallbackManager;
  deployed(): Promise<FallbackManager>;

  on(event: EventFilter | string, listener: Listener): FallbackManager;
  once(event: EventFilter | string, listener: Listener): FallbackManager;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): FallbackManager;
  removeAllListeners(eventName: EventFilter | string): FallbackManager;
  removeListener(eventName: any, listener: Listener): FallbackManager;

  interface: FallbackManagerInterface;

  functions: {
    setFallbackHandler(
      handler: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  setFallbackHandler(
    handler: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    setFallbackHandler(handler: string): Promise<BigNumber>;
  };
}
