/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { TransactionOverrides } from ".";
import { FallbackManager } from "./FallbackManager";

export class FallbackManagerFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: TransactionOverrides): Promise<FallbackManager> {
    return super.deploy(overrides) as Promise<FallbackManager>;
  }
  getDeployTransaction(overrides?: TransactionOverrides): UnsignedTransaction {
    return super.getDeployTransaction(overrides);
  }
  attach(address: string): FallbackManager {
    return super.attach(address) as FallbackManager;
  }
  connect(signer: Signer): FallbackManagerFactory {
    return super.connect(signer) as FallbackManagerFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FallbackManager {
    return new Contract(address, _abi, signerOrProvider) as FallbackManager;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "handler",
        type: "address"
      }
    ],
    name: "setFallbackHandler",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    payable: true,
    stateMutability: "payable",
    type: "fallback"
  }
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101d5806100206000396000f3fe60806040526004361061003a577c01000000000000000000000000000000000000000000000000000000006000350463f08a032381146100ba575b6000341180610047575036155b15610051576100b8565b7f6c9a6c4a39284e37ed1cf53d337577d14212a4870fb976a4366c693b939918d5805473ffffffffffffffffffffffffffffffffffffffff8116156100b557366000803760008036600080855af13d6000803e8015156100b0573d6000fd5b3d6000f35b50505b005b3480156100c657600080fd5b506100b8600480360360208110156100dd57600080fd5b503573ffffffffffffffffffffffffffffffffffffffff1633301461014d576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602c81526020018061017e602c913960400191505060405180910390fd5b61015681610159565b50565b7f6c9a6c4a39284e37ed1cf53d337577d14212a4870fb976a4366c693b939918d55556fe4d6574686f642063616e206f6e6c792062652063616c6c65642066726f6d207468697320636f6e7472616374a165627a7a7230582031f72ffd4227e519547a86535c7198138f7b7d04cc42568a13b2e3721783fa460029";
