/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { TransactionOverrides } from ".";
import { GnosisProxy } from "./GnosisProxy";

export class GnosisProxyFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _masterCopy: string,
    overrides?: TransactionOverrides
  ): Promise<GnosisProxy> {
    return super.deploy(_masterCopy, overrides) as Promise<GnosisProxy>;
  }
  getDeployTransaction(
    _masterCopy: string,
    overrides?: TransactionOverrides
  ): UnsignedTransaction {
    return super.getDeployTransaction(_masterCopy, overrides);
  }
  attach(address: string): GnosisProxy {
    return super.attach(address) as GnosisProxy;
  }
  connect(signer: Signer): GnosisProxyFactory {
    return super.connect(signer) as GnosisProxyFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GnosisProxy {
    return new Contract(address, _abi, signerOrProvider) as GnosisProxy;
  }
}

const _abi = [
  {
    inputs: [
      {
        name: "_masterCopy",
        type: "address"
      }
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor"
  },
  {
    payable: true,
    stateMutability: "payable",
    type: "fallback"
  }
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516020806101858339810180604052602081101561003057600080fd5b5051600160a060020a0381161515610093576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260248152602001806101616024913960400191505060405180910390fd5b60008054600160a060020a03909216600160a060020a0319909216919091179055609f806100c26000396000f3fe608060405273ffffffffffffffffffffffffffffffffffffffff600054167fa619486e0000000000000000000000000000000000000000000000000000000060003514156050578060005260206000f35b3660008037600080366000845af43d6000803e801515606e573d6000fd5b3d6000f3fea165627a7a7230582071e478cbe4e3b6ad8d63995a70684cc226e56494c7ecda32d393b7597a1e4b2a0029496e76616c6964206d617374657220636f707920616464726573732070726f7669646564";
