/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IProxyCreationCallback } from "./IProxyCreationCallback";

export class IProxyCreationCallbackFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProxyCreationCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IProxyCreationCallback;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "proxy",
        type: "address"
      },
      {
        name: "_mastercopy",
        type: "address"
      },
      {
        name: "initializer",
        type: "bytes"
      },
      {
        name: "saltNonce",
        type: "uint256"
      }
    ],
    name: "proxyCreated",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  }
];
