/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IProxyInterface extends Interface {
  functions: {
    masterCopy: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class IProxy extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IProxy;
  attach(addressOrName: string): IProxy;
  deployed(): Promise<IProxy>;

  on(event: EventFilter | string, listener: Listener): IProxy;
  once(event: EventFilter | string, listener: Listener): IProxy;
  addListener(eventName: EventFilter | string, listener: Listener): IProxy;
  removeAllListeners(eventName: EventFilter | string): IProxy;
  removeListener(eventName: any, listener: Listener): IProxy;

  interface: IProxyInterface;

  functions: {
    masterCopy(): Promise<string>;
  };

  masterCopy(): Promise<string>;

  filters: {};

  estimate: {
    masterCopy(): Promise<BigNumber>;
  };
}
