/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ISignatureValidatorInterface extends Interface {
  functions: {
    isValidSignature: TypedFunctionDescription<{
      encode([_data, _signature]: [Arrayish, Arrayish]): string;
    }>;
  };

  events: {};
}

export class ISignatureValidator extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ISignatureValidator;
  attach(addressOrName: string): ISignatureValidator;
  deployed(): Promise<ISignatureValidator>;

  on(event: EventFilter | string, listener: Listener): ISignatureValidator;
  once(event: EventFilter | string, listener: Listener): ISignatureValidator;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): ISignatureValidator;
  removeAllListeners(eventName: EventFilter | string): ISignatureValidator;
  removeListener(eventName: any, listener: Listener): ISignatureValidator;

  interface: ISignatureValidatorInterface;

  functions: {
    isValidSignature(_data: Arrayish, _signature: Arrayish): Promise<string>;
  };

  isValidSignature(_data: Arrayish, _signature: Arrayish): Promise<string>;

  filters: {};

  estimate: {
    isValidSignature(_data: Arrayish, _signature: Arrayish): Promise<BigNumber>;
  };
}
