/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { TransactionOverrides } from ".";
import { MasterCopy } from "./MasterCopy";

export class MasterCopyFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: TransactionOverrides): Promise<MasterCopy> {
    return super.deploy(overrides) as Promise<MasterCopy>;
  }
  getDeployTransaction(overrides?: TransactionOverrides): UnsignedTransaction {
    return super.getDeployTransaction(overrides);
  }
  attach(address: string): MasterCopy {
    return super.attach(address) as MasterCopy;
  }
  connect(signer: Signer): MasterCopyFactory {
    return super.connect(signer) as MasterCopyFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MasterCopy {
    return new Contract(address, _abi, signerOrProvider) as MasterCopy;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_masterCopy",
        type: "address"
      }
    ],
    name: "changeMasterCopy",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "masterCopy",
        type: "address"
      }
    ],
    name: "ChangedMasterCopy",
    type: "event"
  }
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610231806100206000396000f3fe608060405234801561001057600080fd5b5060043610610047577c010000000000000000000000000000000000000000000000000000000060003504637de7edef811461004c575b600080fd5b61007f6004803603602081101561006257600080fd5b503573ffffffffffffffffffffffffffffffffffffffff16610081565b005b3330146100d9576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602c8152602001806101da602c913960400191505060405180910390fd5b73ffffffffffffffffffffffffffffffffffffffff81161515610147576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260248152602001806101b66024913960400191505060405180910390fd5b6000805473ffffffffffffffffffffffffffffffffffffffff831673ffffffffffffffffffffffffffffffffffffffff19909116811790915560408051918252517f75e41bc35ff1bf14d81d1d2f649c0084a0f974f9289c803ec9898eeec4c8d0b89181900360200190a15056fe496e76616c6964206d617374657220636f707920616464726573732070726f76696465644d6574686f642063616e206f6e6c792062652063616c6c65642066726f6d207468697320636f6e7472616374a165627a7a723058202e76b8f2757bf6b8024b0890a11b8d8e482221ec4a8bc9823852cacd3df0e6f70029";
