/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ModuleInterface extends Interface {
  functions: {
    manager: TypedFunctionDescription<{ encode([]: []): string }>;

    changeMasterCopy: TypedFunctionDescription<{
      encode([_masterCopy]: [string]): string;
    }>;
  };

  events: {
    ChangedMasterCopy: TypedEventDescription<{
      encodeTopics([masterCopy]: [null]): string[];
    }>;
  };
}

export class Module extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Module;
  attach(addressOrName: string): Module;
  deployed(): Promise<Module>;

  on(event: EventFilter | string, listener: Listener): Module;
  once(event: EventFilter | string, listener: Listener): Module;
  addListener(eventName: EventFilter | string, listener: Listener): Module;
  removeAllListeners(eventName: EventFilter | string): Module;
  removeListener(eventName: any, listener: Listener): Module;

  interface: ModuleInterface;

  functions: {
    manager(): Promise<string>;

    changeMasterCopy(
      _masterCopy: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  manager(): Promise<string>;

  changeMasterCopy(
    _masterCopy: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    ChangedMasterCopy(masterCopy: null): EventFilter;
  };

  estimate: {
    manager(): Promise<BigNumber>;

    changeMasterCopy(_masterCopy: string): Promise<BigNumber>;
  };
}
