/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface Proxy1Interface extends Interface {
  functions: {};

  events: {};
}

export class Proxy1 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Proxy1;
  attach(addressOrName: string): Proxy1;
  deployed(): Promise<Proxy1>;

  on(event: EventFilter | string, listener: Listener): Proxy1;
  once(event: EventFilter | string, listener: Listener): Proxy1;
  addListener(eventName: EventFilter | string, listener: Listener): Proxy1;
  removeAllListeners(eventName: EventFilter | string): Proxy1;
  removeListener(eventName: any, listener: Listener): Proxy1;

  interface: Proxy1Interface;

  functions: {};

  filters: {};

  estimate: {};
}
